import React, { useEffect, useRef, useState } from "react";
import { Bot, Loader2 } from "lucide-react";
import { getAnalystReport } from "../services/api";
import { font, color, gradients } from "../theme";

// On-demand AI incident report with a typewriter reveal. Never called
// automatically — only when the presenter clicks, so it can never slow down
// or interfere with a scan. Falls back to a rule-based report server-side if
// no LLM key is configured, so this panel always has something to show.
export default function AnalystPanel({ detection }) {
  const [loading, setLoading] = useState(false);
  const [full, setFull] = useState("");
  const [shown, setShown] = useState("");
  const [source, setSource] = useState(null);
  const [error, setError] = useState(null);
  const timerRef = useRef(null);

  useEffect(() => () => clearInterval(timerRef.current), []);

  const run = async () => {
    setLoading(true); setError(null); setFull(""); setShown(""); setSource(null);
    try {
      const res = await getAnalystReport(detection);
      setFull(res.report || "");
      setSource(res.source);
    } catch {
      setError("AI Analyst unavailable right now.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!full) return;
    let i = 0;
    clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      i += 3;
      setShown(full.slice(0, i));
      if (i >= full.length) clearInterval(timerRef.current);
    }, 12);
    return () => clearInterval(timerRef.current);
  }, [full]);

  return (
    <div style={{ borderRadius: 14, border: "1px solid rgba(94,234,212,.2)", background: "rgba(94,234,212,.04)", padding: 16 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: shown ? 10 : 0 }}>
        <h4 style={{ margin: 0, display: "flex", alignItems: "center", gap: 8, fontFamily: font.display, fontWeight: 700, fontSize: 13, color: color.text }}>
          <Bot size={15} color={color.cyan} /> AI Analyst
        </h4>
        <button onClick={run} disabled={loading}
          style={{ fontSize: 11, padding: "6px 14px", borderRadius: 99, border: "1px solid rgba(94,234,212,.3)", background: "rgba(94,234,212,.08)", color: color.cyan, cursor: loading ? "default" : "pointer", opacity: loading ? 0.6 : 1, display: "flex", alignItems: "center", gap: 6, fontFamily: font.body }}>
          {loading && <Loader2 size={12} style={{ animation: "zSpin .7s linear infinite" }} />}
          {loading ? "Analyzing…" : full ? "Regenerate" : "Generate incident report"}
        </button>
      </div>
      {error && <p style={{ color: color.redLight, fontSize: 12 }}>{error}</p>}
      {shown && (
        <p style={{ fontSize: 12.5, color: "rgba(237,235,255,.78)", lineHeight: 1.6, whiteSpace: "pre-wrap", margin: 0 }}>
          {shown}
          {shown.length < full.length && <span style={{ animation: "zPulse 1s infinite" }}>▍</span>}
        </p>
      )}
      {source && shown.length >= full.length && full.length > 0 && (
        <p style={{ fontFamily: font.mono, fontSize: 9.5, letterSpacing: ".08em", color: "rgba(237,235,255,.35)", marginTop: 10, marginBottom: 0 }}>
          {source === "groq" ? "GENERATED BY AI ANALYST · LLAMA 3.3 70B" : "GENERATED FROM THE RULE-BASED EXPLAINABILITY ENGINE"}
        </p>
      )}
    </div>
  );
}
